.TH wudi 8 "29 Februar, 2011" "version 0.1" "Linux System Administrator's Manual"
.SH NAME
wudi \- Working Unit Director
.SH SYNOPSIS
.B wudi
listenip listenport reposip reposport
.P
.SH DESCRIPTION
wudi is a small high performance repository director. It was created by Working Unit and based on the HTTP Protocol.
.TP
.SH FILES
.P
/var/log/wudi.log
.SH AUTHOR
Ripx80
